name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "saigopi123456" --password-stdin
        docker image build -t saigopi123456/pyflask:latest .
        docker push saigopi123456/pyflask:latest
